import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useQuery } from '@apollo/client';
import { ANIME__LIST } from './queries/query';
import Card from './components/Card';
import { Container } from '../styles/uielement';

const Home: NextPage = () => {
  const { data, loading, error } = useQuery(ANIME__LIST);

  if (loading) return <h1>Loading...</h1>;
  if (error) return <h1>Error</h1>;
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Anime List</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container>
        <h1>Anime List</h1>
        <Card />
      </Container>
    </div>
  );
};

export default Home;
