import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Container } from '../styles/uielement';
import ListCard from '../components/ListCard';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anime List</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <h1>Anime List</h1>
      </header>
      <Container>
        <ListCard />
      </Container>
    </div>
  );
};

export default Home;
